#!/usr/bin/python3

import sys, os
from database import Database

entrada = sys.argv[1] if sys.argv[1:] else sys.exit()
name = sys.argv[2] if sys.argv[2:] else sys.exit()

db = Database()
services = db.getDataServiceAll()

if entrada == 'setting':
	setting = db.getDataSetting()
	setting['state'] = name
	db.updateSetting(setting)

state = sys.argv[3] if sys.argv[3:] else sys.exit()
if entrada == 'service':
	service = db.getDataService(name)
	if service:
		service['state'] = state
		db.saveService(service)


